export const CREATE_GAME_CODE = "CREATE_GAME_CODE";
export const CREATE_GAME_ERROR = "CREATE_GAME_ERROR";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";

export const CREATE_RANDOM_GAME = "CREATE_RANDOM_GAME";
export const CREATE_RANDOM_GAME_ERROR = "CREATE_RANDOM_GAME_ERROR";
export const CREATE_RANDOM_GAME_SUCCESS = "CREATE_RANDOM_GAME_SUCCESS";

export const CREATE_GAME_WITH_AI = "CREATE_GAME_WITH_AI";
export const CREATE_GAME_WITH_AI_ERROR = "CREATE_GAME_WITH_AI_ERROR";
export const CREATE_GAME_WITH_AI_SUCCESS = "CREATE_GAME_WITH_AI_SUCCESS";

export const JOIN_GAME_WITH_CODE = "JOIN_GAME_WITH_CODE";
export const JOIN_GAME_WITH_CODE_ERROR = "JOIN_GAME_WITH_ERROR";
export const JOIN_GAME_WITH_CODE_SUCCESS = "JOIN_GAME_WITH_SUCCESS";

export const GET_CURRENT_GAME = 'GET_CURRENT_GAME';
export const CLEAR_GAME = 'CLEAR_GAME'
