import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
 ru:{
   randPlay:"Игра со случайным соперником",
   aiPlay:"Игра с ИИ",
   closePlay:"Закрытая игра",
   rating:"Рейтинг игроков",
   profile:"Профиль",
   rules:"Правила Го",
   back:"Назад",
   lang:"EN",
   exit:"Выход",
   win:"Победа",
   file:"Файл",
   log:"Лог",
   defeat:"Поражение",
   place:"Рейтинг",
   score:"Счёт",
   waitRandom:"Ожидание случайного соперника",
   together:"Вместе с Вами готовы сыграть:",
   cancel:"Отмена",
   menu:"Меню",
   giveup:"Сдаться",
   pass:"Пас",
   takeHints:"Взять подсказку",
   id:"ID игры",
   create: "Создать игру",
   join: "Присоединиться к игре",
   search: "Введите ник игрока или его место",
   rulesLink: 'https://ufgo.org/Rules9x9/Go%20Rules%209x9.htm',
   giveUpPhrase: 'Ты уверен? Дорогу осилит идущий...',
   hintBestOf3: 'Показать лучший из заданных 3 ходов', 
   hintBestMoveQuarter: 'В какой четверти доски сейчас лучший ход?',
   hintWinner:'Кто побеждает на данный момент?',
   hintGoodMovesArea: 'В какой области хороший ход?',
   hintBestMove:'Лучший ход', 
   hintGoodMove:'5 попыток найти хороший ход!',
   hintAtari:'Атари',
   hintTitleBestOf3: 'Показывает лучший из заданных трех ходов (стоимость 2)', 
   hintTitleBestMoveQuarter: 'Показывает четверть доски в которой есть лучший ход (стоимость 1)',
   hintTitleWinner:'Показывает кто побеждает на данный момент (стоимость 1)',
   hintTitleGoodMovesArea: 'Показывает область размером 7х7 в которой есть максимальное количество удачных ходов (стоимость 2)',
   hintTitleBestMove:'Показывает область в которой есть лучший ход, если пользователь не угадывает этот ход зона уменьшается (стоимость 3)', 
   hintTitleGoodMove:'Если выбранный ход нельзя назвать хорошим, пользователю дается еще одна попытка (стоимость 3)',
   hintTitleAtari:'Показывает последние дыхание у камня или группы камней (стоимость 0)',
   youWin: 'Победил!',
   youLose: 'Проиграл!',
   scoreByHints: 'Очки по подсказкам',
   scoreFinal:'Итоговые очки',
   waitSecond: 'Ожидание второго игрока',
   opponentFound: 'Противник найден!',
   opponentConnected:"Игрок подключился!",
   connectionFailed:"Не удалось подключиться к запрашиваемой игре",
   wait: 'Ожидайте',
   startGame:'Начать игру',
   gameCodeTitle: 'Код вашей игры',
   gameCodeField: 'Укажите код игры',
   tryAgainTitle:'Попробовать еще раз',
   upTitle:'Вернуться к началу',
   enterAll: 'Заполните все поля',
   register: 'Зарегистрироваться',
   auth: 'Войти',
   submit: 'Далее',
   makeMove: ' сделал ход ',
   playerPassed: ' спасовал '
 },
 en: {
  randPlay:"Play with a random opponent",
  aiPlay:"Play with AI",
  closePlay:"Private game",
  rating:"Leaderboard",
  profile:"Profile",
  rules:"Go rules",
  back:"Back",
  lang:"RU",
  exit:"Exit",
  win:"Win",
  file:"File",
  log:"Log",
  defeat:"Defeat",
  place:"Place",
  score:"Score",
  waitRandom:"Waiting for a random opponent",
  together:"Ready to play with you:",
  cancel:"Cancel",
  menu:"Menu",
  giveup:"Give up",
  pass:"Pass",
  takeHints:"Take a hint",
  id:"Game ID",
  create:"Create a game",
  join:"Join the game",
  search: "Enter player's nickname or place",
  rulesLink: "https://www.britgo.org/intro/intro2.html",
  giveUpPhrase: "Success is not final; failure is not fatal: It is the courage to continue that counts.",
  hintBestOf3: 'Show the best of the given 3 moves', 
  hintBestMoveQuarter: 'Which quarter of the board is the best move now?',
  hintWinner:'Who is winning so far?',
  hintGoodMovesArea: 'In which area is a good move?',
  hintBestMove:'Best move', 
  hintGoodMove:'5 attempts to find a good move!',
  hintAtari:'Atari',
  hintTitleBestOf3: 'Shows the best of the given three moves (cost 2)', 
  hintTitleBestMoveQuarter: 'Shows the quarter of the board with the best move (cost 1)',
  hintTitleWinner:'Shows who is currently winning (cost 1)',
  hintTitleGoodMovesArea: 'Shows a 7x7 area that has the maximum number of successful moves (cost 2)',
  hintTitleBestMove:'Shows the area in which there is a best move, if the user does not guess this move the area decreases (cost 3)', 
  hintTitleGoodMove:'If the chosen move is not good, the user is given another try (cost 3)',
  hintTitleAtari:'Shows the last breath of a stone or group of stones (cost 0)',
  youWin: 'You win!',
  youLose: 'You lose!',
  scoreByHints: 'Score by hints',
   scoreFinal:'Final score',
   waitSecond: 'Waiting for second player',
   opponentFound: 'Opponent has been found!',
   opponentConnected:"Opponent connected!",
   connectionFailed:"Connection failed",
   wait: 'Please wait',
   startGame:'Start the game',
   gameCodeTitle: 'Your game code',
   gameCodeField: 'Enter game code',
   tryAgainTitle:'Try again',
   upTitle:'Go up',
   enterAll: 'Fill in all the fields',
   register: 'Sign up',
   auth: 'sign in',
   submit: 'Submit',
   makeMove: ' make move ',
   playerPassed: ' passed ',
 }
});