import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
 ru:{
   randPlay:"Игра со случайным соперником",
   aiPlay:"Игра с ИИ",
   closePlay:"Закрытая игра",
   rating:"Рейтинг игроков",
   profile:"Профиль",
   rules:"Правила Го",
   back:"Назад",
   lang:"EN",
   exit:"Выход",
   win:"Победа",
   file:"Файл",
   log:"Лог",
   defeat:"Поражение",
   place:"Рейтинг",
   score:"Счёт",
   wait1:"Ожидание случайного соперника",
   together:"Вместе с Вами готовы сыграть:",
   cancel:"Отмена",
   menu:"Меню",
   giveup:"Сдаться",
   pass:"Пас",
   takeHints:"Взять подсказку",
   id:"ID игры",
   create: "Создать игру",
   join: "Присоединиться к игре",
   search: "Введите ник игрока"
 },
 en: {
  randPlay:"Play with a random opponent",
  aiPlay:"Play with AI",
  closePlay:"Private game",
  rating:"Leaderboard",
  profile:"Profile",
  rules:"Go rules",
  back:"Back",
  lang:"RU",
  exit:"Exit",
  win:"Win",
  file:"File",
  log:"Log",
  defeat:"Defeat",
  place:"Place",
  score:"Score",
  wait1:"Waiting for a random opponent",
  together:"Ready to play with you:",
  cancel:"Cancel",
  menu:"Menu",
  giveup:"Give up",
  pass:"Pass",
  takeHints:"Take a hint",
  id:"Game ID",
  create:"Create a game",
  join:"Join the game",
  search: "Enter player's nickname"
 }
});