export const SINGLE_HELP = "SINGLE_HELP";
export const MAP_STONES = "MAP_STONES";
export const MULTIPLE_HELP = "MULTIPLE_HELP";
export const MARKERS_CLEAR = "MARKERS_CLEAR";
export const MAP_HELP = "MAP_HELP";
export const ATARI_HELP = "ATARI_HELP";
export const WINNER_USER = "WINNER_USER";
export const LOSER_USER = "LOSER_USER";
export const SET_BLOCKED = "SET_BLOCKED";
export const SCORES = "SCORES";
export const SCORES_WINNER = "SCORES_WINNER";
export const GET_SCORES_WINNER = "GET_SCORES_WINNER";

export const GET_HINT_BEST_MOVES = "GET_HINT_BEST_MOVES";
export const GET_HINT_ATARI = "GET_HINT_ATARI";
export const GET_HINT_SHOW_BEST = "GET_HINT_SHOW_BEST";
export const GET_HINT_HEATMAP_FULL = "GET_HINT_HEATMAP_FULL";

export const GET_HINT_HEATMAP = "GET_HINT_HEATMAP";

export const GET_HINT_HEATMAP_ZONE = "GET_HINT_HEATMAP_ZONE";
